name: FeatherLib
version: '${project.version}'
main: uk.mqchinee.featherlib.FeatherLib
author: mqchinee
api-version: 1.18
softdepend:
  - Vault
  - PlaceholderAPI
permissions:
  feather.info:
    default: op
commands:
  feather:
    permission: feather.info
