name: Archelia
version: '${project.version}'
main: uk.mqchinee.archelia.Archelia
author: mqchinee
api-version: 1.18
folia-supported: true
softdepend:
  - Vault
permissions:
  archelia.info:
    default: op
commands:
  archelia: {}
