name: FeatherAPI
version: '1.0.1'
main: uk.mqchinee.featherapi.FeatherAPI
author: mqchinee
api-version: 1.18
softdepend:
  - PlaceholderAPI
  - Vault
permissions:
  feather-api.info:
    default: op
commands:
  feather-api:
    permission: feather-api.info
