name: LanternCore
version: '1.0-RELEASE'
main: uk.mqchinee.lanterncore.LanternCore
author: mqchinee
api-version: 1.18
softdepend:
  - Vault
  - PlaceholderAPI
permissions:
  lantern.info:
    default: op
commands:
  lantern:
    permission: lantern.info
